/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as LendingRouteImport } from './routes/lending'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletWithdrawRouteImport } from './routes/wallet.withdraw'
import { Route as WalletSendRouteImport } from './routes/wallet.send'
import { Route as WalletReceiveRouteImport } from './routes/wallet.receive'
import { Route as WalletMoveOutRouteImport } from './routes/wallet.move-out'
import { Route as WalletMoveInRouteImport } from './routes/wallet.move-in'
import { Route as WalletDepositRouteImport } from './routes/wallet.deposit'
import { Route as ReservesIdRouteImport } from './routes/reserves.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const LendingRoute = LendingRouteImport.update({
  id: '/lending',
  path: '/lending',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletWithdrawRoute = WalletWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => WalletRoute,
} as any)
const WalletSendRoute = WalletSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => WalletRoute,
} as any)
const WalletReceiveRoute = WalletReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => WalletRoute,
} as any)
const WalletMoveOutRoute = WalletMoveOutRouteImport.update({
  id: '/move-out',
  path: '/move-out',
  getParentRoute: () => WalletRoute,
} as any)
const WalletMoveInRoute = WalletMoveInRouteImport.update({
  id: '/move-in',
  path: '/move-in',
  getParentRoute: () => WalletRoute,
} as any)
const WalletDepositRoute = WalletDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => WalletRoute,
} as any)
const ReservesIdRoute = ReservesIdRouteImport.update({
  id: '/reserves/$id',
  path: '/reserves/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/lending': typeof LendingRoute
  '/wallet': typeof WalletRouteWithChildren
  '/reserves/$id': typeof ReservesIdRoute
  '/wallet/deposit': typeof WalletDepositRoute
  '/wallet/move-in': typeof WalletMoveInRoute
  '/wallet/move-out': typeof WalletMoveOutRoute
  '/wallet/receive': typeof WalletReceiveRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/lending': typeof LendingRoute
  '/wallet': typeof WalletRouteWithChildren
  '/reserves/$id': typeof ReservesIdRoute
  '/wallet/deposit': typeof WalletDepositRoute
  '/wallet/move-in': typeof WalletMoveInRoute
  '/wallet/move-out': typeof WalletMoveOutRoute
  '/wallet/receive': typeof WalletReceiveRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/lending': typeof LendingRoute
  '/wallet': typeof WalletRouteWithChildren
  '/reserves/$id': typeof ReservesIdRoute
  '/wallet/deposit': typeof WalletDepositRoute
  '/wallet/move-in': typeof WalletMoveInRoute
  '/wallet/move-out': typeof WalletMoveOutRoute
  '/wallet/receive': typeof WalletReceiveRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/history'
    | '/lending'
    | '/wallet'
    | '/reserves/$id'
    | '/wallet/deposit'
    | '/wallet/move-in'
    | '/wallet/move-out'
    | '/wallet/receive'
    | '/wallet/send'
    | '/wallet/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/history'
    | '/lending'
    | '/wallet'
    | '/reserves/$id'
    | '/wallet/deposit'
    | '/wallet/move-in'
    | '/wallet/move-out'
    | '/wallet/receive'
    | '/wallet/send'
    | '/wallet/withdraw'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/history'
    | '/lending'
    | '/wallet'
    | '/reserves/$id'
    | '/wallet/deposit'
    | '/wallet/move-in'
    | '/wallet/move-out'
    | '/wallet/receive'
    | '/wallet/send'
    | '/wallet/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  LendingRoute: typeof LendingRoute
  WalletRoute: typeof WalletRouteWithChildren
  ReservesIdRoute: typeof ReservesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lending': {
      id: '/lending'
      path: '/lending'
      fullPath: '/lending'
      preLoaderRoute: typeof LendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/withdraw': {
      id: '/wallet/withdraw'
      path: '/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof WalletWithdrawRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/send': {
      id: '/wallet/send'
      path: '/send'
      fullPath: '/wallet/send'
      preLoaderRoute: typeof WalletSendRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/receive': {
      id: '/wallet/receive'
      path: '/receive'
      fullPath: '/wallet/receive'
      preLoaderRoute: typeof WalletReceiveRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/move-out': {
      id: '/wallet/move-out'
      path: '/move-out'
      fullPath: '/wallet/move-out'
      preLoaderRoute: typeof WalletMoveOutRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/move-in': {
      id: '/wallet/move-in'
      path: '/move-in'
      fullPath: '/wallet/move-in'
      preLoaderRoute: typeof WalletMoveInRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/deposit': {
      id: '/wallet/deposit'
      path: '/deposit'
      fullPath: '/wallet/deposit'
      preLoaderRoute: typeof WalletDepositRouteImport
      parentRoute: typeof WalletRoute
    }
    '/reserves/$id': {
      id: '/reserves/$id'
      path: '/reserves/$id'
      fullPath: '/reserves/$id'
      preLoaderRoute: typeof ReservesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WalletRouteChildren {
  WalletDepositRoute: typeof WalletDepositRoute
  WalletMoveInRoute: typeof WalletMoveInRoute
  WalletMoveOutRoute: typeof WalletMoveOutRoute
  WalletReceiveRoute: typeof WalletReceiveRoute
  WalletSendRoute: typeof WalletSendRoute
  WalletWithdrawRoute: typeof WalletWithdrawRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletDepositRoute: WalletDepositRoute,
  WalletMoveInRoute: WalletMoveInRoute,
  WalletMoveOutRoute: WalletMoveOutRoute,
  WalletReceiveRoute: WalletReceiveRoute,
  WalletSendRoute: WalletSendRoute,
  WalletWithdrawRoute: WalletWithdrawRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  LendingRoute: LendingRoute,
  WalletRoute: WalletRouteWithChildren,
  ReservesIdRoute: ReservesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
